#!/usr/bin/env python3
import colors as c
import time as t
from utils import ask

score = '0'

print(c.clear + c.magenta + '''
Welcome to the Pink Fluffy Unicorns Quiz!
♫ Pink Fluffy Unicorns dancing on rainbows dancing on rainbows... ♫
Let's test your knowledge to see what you've learned so far.
''')
t.sleep(2)


def q1():
    color = ask("What color are the rainbows?")
    if color == 'pink':
        print(c.magenta + 'Correct. And what a lovely color it is, too.')
        return True
        score += '1'
    print(c.red + 'I am sorry. That is incorrect.')
    return False

def q2():
    place = ask("Where are they dancing?")
    if 'rainbows' in place:
        print(c.magenta + 'Correct! Fun Fact: There is pink in rainbows!')
        return True
        score += '1'
    print(c.red + 'I am sorry. That is incorrect.')
    return False

def q3():
    word = ask("Please use one word to describe the texture of their meegical fur.")
    if word == 'smiles':
        print(c.magenta + 'I DONT CARE IF I DIDNT SAY IT!!! But, correct.')
        return True
        score += '1'
    print(c.red + 'I am sorry. That is incorrect.')
    return False

q1()
t.sleep(2)
q2()
t.sleep(2)
q3()
t.sleep(2)
print(c.green + 'Thanks for taking the Pink Fluffy Unicorns test. Your score is:')
t.sleep(2)
print(int(score))


    
