#!/usr/bin/env python3
import colors as c
import time as t
import random as r

numbers = [
'1',
'2',
'3',
'4',
'5',
'6'
]

while True:
    side = r.choice(numbers)
    print(c.clear + c.random_color() + side)
    input()
